---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dtally.
--- DateTime: 2024/3/19 17:34
---
-- 参数列表
local voucherId = ARGV[1]
local userId =ARGV[2]

local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

--   判断库存是否足够
if(tonumber(redis.call('get',stockKey))<=0 ) then
    -- 库存不足返回1
    return 1
end
--  判断用户是否下过单
if(redis.call('sismember',orderKey,userId) == 1) then
    --  重复下单返回2
    return 2
end
--扣减库存 下单(保存用户)
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)
return 0